/**
 * Welcome to Cloudflare Workers! This is your first worker.
 *
 * - Run `npm run dev` in your terminal to start a development server
 * - Open a browser tab at http://localhost:8787/ to see your worker in action
 * - Run `npm run deploy` to publish your worker
 *
 * Bind resources to your worker in `wrangler.jsonc`. After adding bindings, a type definition for the
 * `Env` object can be regenerated with `npm run cf-typegen`.
 *
 * Learn more at https://developers.cloudflare.com/workers/
 */

type UnauthorizedJson = {
	error: "unauthorized";
};

type ApiKeyId = string;

interface ApiKeyRecord {
	/**
	 * Human-friendly identifier (ex: "guild-a"). Not secret.
	 * Useful for future audit logs / per-guild limits.
	 */
	id: ApiKeyId;
	/** Lowercase hex SHA-256 of the *raw* API key that bots send. */
	sha256: string;
	/** If true, this key is treated as revoked. */
	disabled?: boolean;
}

interface ApiKeyConfig {
	keys: ApiKeyRecord[];
}

/**
 * `Env` is generated by `wrangler types` into `worker-configuration.d.ts`.
 * Required secrets:
 * - HYPIXEL_API_KEY
 * - GUILD_API_KEYS
 */

type AuthResult =
	| { ok: true; apiKeyId: ApiKeyId }
	| { ok: false };

let apiKeyConfigCache: {
	raw: string;
	config: ApiKeyConfig;
} | null = null;

function unauthorized(): Response {
	return Response.json(
		{ error: "unauthorized" } satisfies UnauthorizedJson,
		{
			status: 401,
			headers: {
				"Cache-Control": "no-store",
				"WWW-Authenticate": "Bearer",
			},
		},
	);
}

function parseBearerToken(authorizationHeader: string | null): string | null {
	if (!authorizationHeader) return null;

	// RFC 9110: auth scheme names are case-insensitive.
	// We accept exactly two whitespace-delimited parts.
	const parts = authorizationHeader.trim().split(/\s+/);
	if (parts.length !== 2) return null;

	const [scheme, token] = parts;
	if (scheme.toLowerCase() !== "bearer") return null;
	if (!token) return null;

	return token;
}

function isLikelySha256Hex(value: string): boolean {
	return /^[0-9a-f]{64}$/.test(value);
}

function constantTimeEqual(a: string, b: string): boolean {
	// Timing-safe compare for equal-length strings.
	if (a.length !== b.length) return false;
	let out = 0;
	for (let i = 0; i < a.length; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i);
	return out === 0;
}

async function sha256Hex(input: string): Promise<string> {
	const bytes = new TextEncoder().encode(input);
	const digest = await crypto.subtle.digest("SHA-256", bytes);
	const hashBytes = new Uint8Array(digest);
	let hex = "";
	for (const b of hashBytes) hex += b.toString(16).padStart(2, "0");
	return hex;
}

function parseApiKeyConfig(secretValue: string): ApiKeyConfig {
	let parsed: unknown;
	try {
		parsed = JSON.parse(secretValue);
	} catch {
		throw new Error("GUILD_API_KEYS must be valid JSON");
	}

	if (
		typeof parsed !== "object" ||
		parsed === null ||
		!("keys" in parsed) ||
		!Array.isArray((parsed as { keys: unknown }).keys)
	) {
		throw new Error("GUILD_API_KEYS must be an object with a 'keys' array");
	}

	const keys = (parsed as { keys: unknown[] }).keys;
	const records: ApiKeyRecord[] = keys.map((k, idx) => {
		if (typeof k !== "object" || k === null) {
			throw new Error(`GUILD_API_KEYS.keys[${idx}] must be an object`);
		}

		const rec = k as Partial<ApiKeyRecord>;
		if (typeof rec.id !== "string" || rec.id.length === 0) {
			throw new Error(`GUILD_API_KEYS.keys[${idx}].id must be a non-empty string`);
		}
		if (typeof rec.sha256 !== "string" || !isLikelySha256Hex(rec.sha256)) {
			throw new Error(
				`GUILD_API_KEYS.keys[${idx}].sha256 must be a 64-char lowercase hex SHA-256`,
			);
		}
		if (rec.disabled !== undefined && typeof rec.disabled !== "boolean") {
			throw new Error(`GUILD_API_KEYS.keys[${idx}].disabled must be a boolean`);
		}

		return {
			id: rec.id,
			sha256: rec.sha256,
			disabled: rec.disabled,
		};
	});

	return { keys: records };
}

function getApiKeyConfig(env: Env): ApiKeyConfig {
	if (apiKeyConfigCache?.raw === env.GUILD_API_KEYS) return apiKeyConfigCache.config;
	const config = parseApiKeyConfig(env.GUILD_API_KEYS);
	apiKeyConfigCache = { raw: env.GUILD_API_KEYS, config };
	return config;
}

async function authenticateRequest(request: Request, env: Env): Promise<AuthResult> {
	const token = parseBearerToken(request.headers.get("Authorization"));
	if (!token) return { ok: false };

	const { keys } = getApiKeyConfig(env);
	const tokenHash = await sha256Hex(token);

	for (const key of keys) {
		if (key.disabled) continue;
		if (constantTimeEqual(key.sha256, tokenHash)) {
			return { ok: true, apiKeyId: key.id };
		}
	}

	return { ok: false };
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);

		let auth: AuthResult;
		try {
			auth = await authenticateRequest(request, env);
		} catch (err) {
			// Fail closed (deny access) if auth config is invalid.
			console.error("Auth configuration error", err);
			return unauthorized();
		}

		if (!auth.ok) return unauthorized();

		if (url.pathname === "/") {
			return Response.json({
				status: "online",
			});
		}

		if (!url.pathname.startsWith("/player/")) {
			return Response.json(
				{ error: "not found" },
				{ status: 404 },
			);
		}

		const identifier = url.pathname.slice("/player/".length);

		if (!identifier) {
			return Response.json(
				{
					error: 'missing username',
				},
				{
					status: 400,
				},
			);
		}

		const isUuid = /^[0-9a-f]{32}$/i.test(identifier) || /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier);

		let uuid: string;

		if (isUuid) {
			uuid = identifier.replace(/-/g, '').toLowerCase();
		} else {
			const mojangResponse = await fetch(`https://api.mojang.com/users/profiles/minecraft/${identifier}`);

			if (!mojangResponse.ok) {
				return Response.json(
					{
						error: 'player not found',
					},
					{
						status: 404,
					},
				);
			}

			const mojangData = (await mojangResponse.json()) as {
				id: string;
				name: string;
			};

			uuid = mojangData.id.toLowerCase();
		}

		// Cache by UUID, not by username
		const cache = caches.default;

		const cacheKey = new Request(`${url.origin}/player/${uuid}`);

		const cached = await cache.match(cacheKey);

		if (cached) {
			console.log(`CACHE HIT ${uuid} (${auth.apiKeyId})`);
			const headers = new Headers(cached.headers);
			headers.set("X-Cache", "HIT");
			return new Response(cached.body, {
				status: cached.status,
				statusText: cached.statusText,
				headers,
			});
		}

		console.log(`CACHE MISS ${uuid} (${auth.apiKeyId})`);

		const hypixelUrl = new URL("https://api.hypixel.net/v2/player");
		hypixelUrl.searchParams.set("uuid", uuid);
		hypixelUrl.searchParams.set("key", env.HYPIXEL_API_KEY);

		const hypixelResponse = await fetch(hypixelUrl);

		const hypixelData = await hypixelResponse.json();

		const response = Response.json(hypixelData, {
			headers: {
				"Cache-Control": "public, max-age=60",
				"X-Cache": "MISS",
				// If you later add per-guild authorization rules, consider `Vary: Authorization`.
			},
		});

		ctx.waitUntil(cache.put(cacheKey, response.clone()));

		return response;
	},
};
